### ISSUE TITLE
keys function

### ISSUE THREAD

**Issue by Raynos** [hughfdjackson/persistent-hash-trie#12]
I could use a `keys()` function to get the list of keys stored in a Trie

See https://github.com/Raynos/immutable-hash/blob/master/index.js#L163 where I call `var keys = Object.keys(transient(...))`

**Comment by hughfdjackson** [comment]
seems reasonable; why O(2n) for a fairly common case when you can O(n).

**Comment by hughfdjackson** [comment]
fixed in 2b25974793960d8218170849cdfb3ab0a4c898c4
