### ISSUE TITLE
Add escapable reduce

### ISSUE THREAD

**Issue by hughfdjackson** [hughfdjackson/persistent-hash-trie#20]
Add a version of reduce that can be backed out of (by throwing the correct error?), to allow for less than O(n) iteration (to implement some/any/find style iterators).

**Comment by Raynos** [comment]
dont use errors for stop iteration.

**Comment by hughfdjackson** [comment]
You would suggest doing..?

**Comment by hughfdjackson** [comment]
:D all done.  @Raynos : glad to review if there's a better way to do this.
